services:
  web:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - ./data:/data
      - ./.env:/app/backend/.env:ro
    environment:
      - DB_DIR=/data
    restart: unless-stopped
    networks:
      default:
      zdenovo_public:
        aliases:
          - web

networks:
  zdenovo_public:
    external: true
